spring:
  application:
    name: server-core
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: pguser
    password: 123123123
  flyway:
    locations: classpath:/db/migration/{vendor}

server:
  port: 9000

logging:
  level:
    server: debug